language: node_js
node_js:
  - "8.0"

branches:
  only:
    - master

before_script:
  - yarn global add @angular/cli

script:
  - ng lint
  - ng test --single-run --code-coverage
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master